---

stages:
  - build
  - deploy

build:
  except:
    - tags
  image:
    name: frankhjung/haskell:8.8.4
    entrypoint: [""]
  stage: build
  variables:
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack
  script:
    - cabal user-config update
    - make setup check build test doc exec bench
    - mkdir -p public/ .cabal/
    - cp -pr \
        ${CI_PROJECT_DIR}/dist-newstyle/build/x86_64-linux/ghc-8.8.4/scrapbook-*/doc/html/scrapbook/ \
        public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    paths:
      - cabal.project.local
      - .cabal.config
      - dist/
      - dist-newstyle/
      - .stack/
      - .stack-work/

pages:
  only:
    refs:
      - master
  image: alpine:latest
  stage: deploy
  script:
    - echo Publishing documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
