---

stages:
  - build
  - deploy

variables:
  STACK_ROOT: ${CI_PROJECT_DIR}/.stack

build:
  stage: build
  except:
    - tags
  image:
    name: frankhjung/haskell:9.0.2
    entrypoint: [""]
  script:
    - make clean setup check build test bench doc exec
    - mv $(stack path --local-doc-root)/scrapbook*/ public/
    - mv .stack-work/benchmark-*.html public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack/
      - .stack-work/

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: alpine:latest
  script:
    - echo Publishing documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
