stages:
  - build
  - deploy

build:
  except:
    - tags
  image:
    name: frankhjung/haskell:latest
    entrypoint: [""]
  stage: build
  script:
    - make clean check build doc
  artifacts:
    paths:
      - public

pages:
  only:
    refs:
      - master
  image: alpine:latest
  stage: deploy
  script:
    - echo Publishing documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
