---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image: frankhjung/haskell:9.4.8
  variables:
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack-work
  script:
    - make check
    - make build
    - make test
    - make doc
    - mv $(stack path --local-doc-root)/ public/
    - make bench
    - cp ${STACK_ROOT}/benchmark-*.html public/
    - make exec
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - ${STACK_ROOT}

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  image: alpine:latest
  script:
    - echo Publish documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
