---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image: frankhjung/haskell:9.4.7
  variables:
    RTSOPTS: "+RTS -N1"
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack-work
  script:
    - make check build test bench doc
    - mv $(stack path --local-doc-root)/ public/
    - cp ${STACK_ROOT}/benchmark-*.html public/
    - make exec
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ${STACK_ROOT}

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: alpine:latest
  script:
    - echo Publishing documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
