---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image:
    name: frankhjung/haskell:9.0.2
    entrypoint: [""]
  script:
    - make setup check build test doc exec bench
    - mkdir -p public/
    # yamllint disable-line rule:line-length
    - cp -r dist-newstyle/build/x86_64-linux/ghc-9.0.2/scrapbook-?.?.?/doc/html/scrapbook/* public/
    # yamllint enable-line rule:line-length
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - dist-newstyle/

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: alpine:latest
  script:
    - echo Publishing documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
