---

columns: 80

newline: native

steps:

  - simple_align:
      cases: true
      top_level_patterns: true
      records: true

  - imports:
      align: global
      list_align: after_alias
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true

  - tabs:
      spaces: 2

  - trailing_whitespace: {}

language_extensions:

  - FlexibleContexts
