---

resolver: lts-16.31
arch: x86_64
flags: {}
packages: ['.']
extra-deps:
  - criterion-1.5.7.0
  - directory-1.3.6.0
  - filepath-1.4.2.1
  - fmt-0.6.1.2
  - hspec-2.7.6
  - logict-0.7.0.3
  - mtl-2.2.2
  - QuickCheck-2.13.2
  - random-1.1
  - stm-2.5.0.0
  - text-1.2.4.0
  - transformers-0.5.6.2
