---

arch: x86_64
system-ghc: true
resolver: lts-14.27
allow-newer: true
flags: {}
packages: ['.']
extra-deps:
  - criterion-1.5.6.1
  - directory-1.3.3.0
  - filepath-1.4.2.1
  - hspec-2.7.1
  - mtl-2.2.2
  - QuickCheck-2.13.2
  - random-1.1
  - stm-2.5.0.0
  - transformers-0.5.6.2
# - finite-typelits-0.1.4.2
