---
resolver: lts-19.27
arch: x86_64
flags: {}
packages: ["."]
allow-newer: true
extra-deps:
  - aeson-2.0.3.0
  - bytestring-0.10.12.1
  - criterion-1.5.13.0
  - containers-0.6.4.1
  - directory-1.3.6.2
  - exceptions-0.10.5
  - filepath-1.4.2.1
  - fmt-0.6.3.0
  - free-5.1.9
  - hspec-2.8.5
  - mtl-2.2.2
  - QuickCheck-2.14.2
  - random-1.2.1.1
  - stm-2.5.0.1
  - text-1.2.5.0
  - time-1.9.3
  - transformers-0.5.6.2
