---

name: haskell scrapbook

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      '**'
# yamllint enable

env:
  STACK_ROOT: "${{ github.workspace }}/.stack"

jobs:

  build:

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            .stack/
            .stack-work/
          key: $GITHUB_REF

      - name: setup
        run: |
          stack setup
          stack update
          stack path
          stack query
          stack ls dependencies
          stack clean
          cabal check

      - name: build
        run: stack build --pedantic --no-test

      - name: test
        run: stack test

      - name: benchmark
        # yamllint disable rule:line-length
        run: |
          stack bench scrapbook:bench:myfilterBench --ba '-o .stack-work/benchmark-myfilter.html'
          stack bench scrapbook:bench:myreverseBench --ba '-o .stack-work/benchmark-myreverse.html'
          stack bench scrapbook:bench:polydivisorsBench --ba '-o .stack-work/benchmark-polydivisors.html'
          stack bench scrapbook:bench:recursionschemesBench --ba '-o .stack-work/benchmark-recursionschemes.html'
          stack bench scrapbook:bench:repmaxBench --ba '-o .stack-work/benchmark-repmax.html'
          stack bench scrapbook:bench:subseqsBench --ba '-o .stack-work/benchmark-subseqs.html'
          stack bench scrapbook:bench:zipfoldBench --ba '-o .stack-work/benchmark-zipfold.html'
        # yamllint enable

      - name: document
        if: github.ref == 'refs/heads/master'
        run: stack haddock --no-rerun-tests --no-run-benchmarks

      - name: public
        if: github.ref == 'refs/heads/master'
        run: |
          mv $(stack path --local-doc-root) public/
          mv .stack-work/benchmark-*.html public/

      - name: publish
        if: success() && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
