---

name: haskell scrapbook

on:
  push:
    branches:
      - master
      - 'feature/**'
  check_run:
    types: [rerequested, requested_action]

jobs:

  build:

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v1.0.0
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - name: setup
        run: stack setup

      - name: build
        run: stack build --pedantic --no-test

      - name: test
        run: stack test

      - name: documentation
        run: stack haddock --no-rerun-tests --no-reconfigure

      - name: copy
        run: mv $(stack path --local-doc-root) public/

      - name: publish
        uses: crazy-max/ghaction-github-pages@v0.4.0
        if: success()
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
