---

name: haskell scrapbook

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master, 'feature**']
  check_run:
    types: [rerequested, requested_action]

jobs:

  build:

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v1.0.0
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            .stack/
            .stack-work/
          key: $GITHUB_REF

      - name: setup
        run: |
          stack update
          stack setup
          stack path
          stack query
          stack ls dependencies
          cabal check

      - name: build
        run: stack build --pedantic --no-test

      - name: test
        run: stack test

      - name: benchmark
        # yamllint disable rule:line-length
        run: |
          stack bench scrapbook:bench:myreverseBench --ba '-o .stack-work/benchmark-myreverse.html'
          stack bench scrapbook:bench:polydivisorsBench --ba '-o .stack-work/benchmark-polydivisors.html'
          stack bench scrapbook:bench:repmaxBench --ba '-o .stack-work/benchmark-repmax.html'
          stack bench scrapbook:bench:subseqsBench --ba '-o .stack-work/benchmark-subseqs.html'
          stack bench scrapbook:bench:zipfoldBench --ba '-o .stack-work/benchmark-zipfold.html'
        # yamllint enable

      - name: document
        if: github.ref_name == 'master'
        run: stack haddock

      - name: public
        if: github.ref_name == 'master'
        run: |
          mv $(stack path --local-doc-root) public/
          mv .stack-work/benchmark-*.html public/

      - name: publish
        uses: crazy-max/ghaction-github-pages@v0.4.0
        if: success() && github.ref_name == 'master'
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
