---

name: haskell scrapbook

on:
  push:
    branches:
      - master
      - 'feature**'
  check_run:
    types: [rerequested, requested_action]

jobs:

  build:

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v1.0.0
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            cabal.project.local
            .cabal.config
            dist/
            dist-newstyle/
            .stack/
            .stack-work/
            .stack-work/
          key: $GITHUB_REF

      - name: setup
        run: |
          cabal new-update --only-dependencies
          cabal new-configure \
            --package-db=clear \
            --package-db=global \
            --package-db=$(stack path --snapshot-pkg-db) \
            --package-db=$(stack path --local-pkg-db)

      - name: build
        run: cabal new-build

      - name: test
        run: cabal new-test --test-show-details=always

      - name: benchmark
        run: cabal new-bench

      - name: document
        run: cabal new-haddock --haddock-quickjump --haddock-hyperlink-source

      - name: copy
        run: |
          mkdir public/
          cp -r \ 
            dist-newstyle/build/x86_64-linux/ghc-*/scrapbook-*/doc/html/scrapbook/* \
            public/

      - name: publish
        uses: crazy-max/ghaction-github-pages@v0.4.0
        if: success()
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
